const perguntasExtremo = [
    "Eu nunca fui preso.",
    "Eu nunca dirigi após ter ingerido bebida alcoólica.",
    "Eu nunca faltei ao trabalho porque estava de ressaca.",
    "Eu nunca cheirei as roupas íntimas de outra pessoa.",
    "Eu nunca cheguei em casa sem me lembrar como.",
    "Eu nunca flertei com um chefe na tentativa de obter uma promoção.",
    "Eu nunca fiz compras no cartão de crédito dos meus pais sem avisá-los.",
    "Eu nunca falsifiquei meus documentos.",
    "Eu nunca vi algum(a) vizinho(a) saindo do banho.",
    "Eu nunca furtei nada em uma loja.",
    "Eu nunca corri da polícia.",
    "Eu nunca cheirei minhas roupas íntimas para conferir se estavam sujas.",
    "Eu nunca fiquei constrangido(a) com cenas picantes enquanto assistia a um filme com os meus pais.",
    "Eu nunca mergulhei sem roupa na piscina.",
    "Eu nunca quebrei algo na casa de alguém e não avisei.",
    "Eu nunca entrei de penetra em uma festa.",
    "Eu nunca fiz uma dieta louca.",
    "Eu nunca criei um perfil falso para _stalkear_ alguém nas redes sociais.",
    "Eu nunca saí sem pagar a conta de um bar/restaurante/boate.",
    "Eu nunca ri até fazer xixi na calça.",
    "Eu nunca olhei o telefone de um namorado ou crush por não confiar ainda.",
    "Eu nunca invadi um local que já estava fechado.",
    "Eu nunca escondi um erro muito grande.",
    "Eu nunca passei uma vergonha em uma viagem.",
    "Eu nunca cometi uma gafe com meu chefe.",
    "Eu nunca menti na entrevista de emprego para ser contratado(a).",
    "Eu nunca fiquei com alguém em um local inusitado.",
    "Eu nunca desisti de um esporte depois de praticá-lo apenas uma vez.",
    "Eu nunca levei uma queda no meio da rua.",
    "Eu nunca dormi no meio da balada por estar bêbado(a).",
    "Eu nunca usei o Tinder.",
    "Eu nunca fiquei com gêmeos.",
    "Eu nunca marquei de ficar com alguém do Tinder.",
    "Eu nunca fiquei com alguém no banheiro de uma festa.",
    "Eu nunca fiquei com alguém na praia.",
    "Eu nunca fiquei com alguém na rua.",
    "Nunca fiquei com alguém do mesmo gênero que eu.",
    "Eu nunca mandei fotos ousadas para alguém.",
    "Eu nunca mandei a mesma foto ousada para duas pessoas ao mesmo tempo.",
    "Eu nunca tive um sonho quente com alguém que está aqui.",
    "Eu nunca acordei ao lado de alguém que não lembrava quem era.",
    "Eu nunca tive um sonho quente com algum professor.",
    "Eu nunca fiquei tão louco que esqueci o próprio nome.",
    "Eu nunca fui carregado para casa depois de dar PT.",
    "Nunca me senti atraído(a) pelo pai/mãe de algum amigo.",
    "Eu nunca enviei fotos ousadas para a pessoa errada.",
    "Eu nunca fiquei com alguém na cama dos meus pais.",
    "Eu nunca dancei especialmente para alguém.",
    "Eu nunca usei o Tinder enquanto namorava.",
    "Eu nunca fui num clube para adultos.",
    "Eu nunca faltei ao trabalho porque estava morrendo de ressaca.",
    "Eu nunca fiquei com alguém que eu nem sabia o nome.",
    "Eu nunca tirei a roupa em uma festa.",
    "Eu nunca mandei uma mensagem sugestiva para um(a) ex, só para provocar.",
    "Eu nunca fiquei com uma pessoa famosa.",
    "Eu nunca tive um 'amigo colorido' ou 'amigo com benefícios'.",
    "Eu nunca fiquei com alguém na universidade.",
    "Eu nunca fingi estar gostando de algo só para agradar o parceiro/a parceira.",
    "Eu nunca fingi estar sóbrio na frente dos meus pais.",
    "Eu nunca acordei e ainda estava bêbado.",
    "Eu nunca nadei sem roupa em uma praia ou cachoeira.",
    "Eu nunca dei um beijo triplo.",
    "Eu nunca fiquei com alguém em um carro.",
    "Eu nunca beijei alguém depois de ter vomitado.",
    "Eu nunca fui trabalhar bêbado.",
    "Eu nunca me passei por outra pessoa nas redes sociais.",
    "Eu nunca dancei em cima de uma mesa.",
    "Eu nunca dei só uma 'passadinha' na casa do ex ou do _crush_.",
    "Eu nunca paguei por conteúdos adultos.",
    "Eu nunca recebi fotos ousadas sem estar esperando.",
    "Eu nunca fui a uma praia de nudismo.",
    "Eu nunca traí alguém em um relacionamento.",
    "Eu nunca menti sobre estar solteiro(a).",
    "Eu nunca fui expulso(a) de algum lugar por mau comportamento.",
    "Eu nunca inventei uma gravidez ou disse que alguém estava grávida pra manipular algo.",
    "Eu nunca forcei alguém a fazer algo que ela não queria.",
    "Eu nunca tive um relacionamento com traições mútuas.",
    "Eu nunca causei um término propositalmente."
  ];