const perguntasPicante = [
    "Nunca fiz sexo em um lugar público.",
    "Nunca fui algemado durante o sexo.",
    "Nunca tive um caso de uma noite.",
    "Nunca enviei um nu para alguém.",
    "Nunca tive uma ménage à trois.",
    "Nunca me encontrei com alguém que acabei de conhecer.",
    "Nunca fiz sexo com a ex de um amigo.",
    "Nunca usei um brinquedo sexual durante o sexo.",
    "Nunca fingi um orgasmo.",
    "Nunca fiz sexo por telefone.",
    "Nunca fui pego masturbando.",
    "Nunca tive sexo em um carro.",
    "Nunca tive relações sexuais com alguém com o dobro da minha idade.",
    "Nunca fiz sexo em um quarto de hotel.",
    "Nunca tive um fraquinho por alguém nesta sala.",
    "Nunca fiz sexo em uma banheira de hidromassagem.",
    "Nunca usei alimentos durante o sexo.",
    "Nunca fiz sexo em uma casa de banho pública.",
    "Nunca enganei um parceiro.",
    "Nunca tive uma relação de amizade com benefícios.",
    "Nunca tive relações sexuais com alguém que conheci on-line.",
    "Nunca fiz sexo em uma piscina.",
    "Nunca fiz sexo enquanto outra pessoa estava assistindo.",
    "Nunca tive um trio com meu parceiro e outra pessoa.",
    "Nunca fiz role-playing durante o sexo.",
    "Nunca beijei alguém após o primeiro encontro.",
    "Nunca menti sobre minha idade para alguém por quem me sentia atraído.",
    "Nunca tive um fraquinho pelo outro amigo significativo de um.",
    "Nunca namorisquei com alguém para conseguir o que eu queria.",
    "Nunca fui magricela com alguém.",
    "Nunca curti com alguém em um lugar público.",
    "Nunca tive um admirador secreto.",
    "Nunca fiz sexo com alguém que eu não achasse atraente.",
    "Nunca tive um beijo apaixonado na chuva.",
    "Nunca me apaixonei à primeira vista.",
    "Nunca tive um sonho romântico com um amigo.",
    "Nunca menti para alguém com quem namorava sobre ser exclusivo.",
    "Nunca namorisquei com alguém enquanto estava em um relacionamento.",
    "Nunca beijei alguém com quem não estava namorando para fazer ciúmes a outra pessoa.",
    "Nunca tive um fraquinho por um professor ou professora.",
    "Nunca tive um engate com alguém que conheci em um aplicativo de namoro.",
    "Nunca tive um encontro romântico com um colega de trabalho.",
    "Nunca tive um fraquinho por alguém significativamente mais velho do que eu.",
    "Nunca curti com alguém enquanto estava sob a influência do álcool.",
    "Nunca sonhei com alguém que eu conhecesse que estivesse em um relacionamento.",
    "Nunca beijei alguém de quem me arrependi imediatamente depois.",
    "Nunca tive uma sessão de maquiagem a vapor em um carro.",
    "Nunca menti sobre meu status de relacionamento para chamar a atenção de alguém.",
    "Nunca namorisquei com alguém enquanto fingia ser outra pessoa on-line.",
    "Nunca beijei alguém e depois agi como se isso nunca tivesse acontecido.",
    "Nunca tive relações sexuais com mais de uma pessoa diariamente.",
    "Nunca fiz parte de uma orgia.",
    "Nunca tive relações sexuais com um estranho.",
    "Nunca tive relações sexuais com alguém mais velho ou mais novo que eu.",
    "Nunca fiz sexo enquanto via pornografia.",
    "Nunca fiz sexo em uma casa de banho pública.",
    "Nunca tive relações sexuais com uma pessoa casada.",
    "Nunca fiz sexo em uma sala com outras pessoas presentes.",
    "Nunca fiz sexo com alguém enquanto seu parceiro estava na mesma sala.",
    "Nunca fiz sexo com alguém que conheci em um bar ou clube.",
    "Nunca fiz sexo com a ex de um amigo.",
    "Nunca tive relações sexuais com alguém enquanto seus pais estavam em casa.",
    "Nunca tive relações sexuais com alguém em um relacionamento com outra pessoa.",
    "Nunca fiz sexo com alguém que não soubesse seu nome.",
    "Nunca tive relações sexuais com uma celebridade em meus sonhos.",
    "Nunca usei algemas ou outras ferramentas BDSM durante o sexo.",
    "Nunca tive relações sexuais com alguém famoso ou conhecido.",
    "Nunca fiz sexo em uma sala de cinema.",
    "Nunca fiz sexo em uma tenda ou acampamento.",
    "Nunca fiz sexo com alguém significativamente mais alto ou mais baixo do que eu.",
    "Nunca fiz sexo em um parque público.",
    "Nunca tive sexo em um barco ou iate.",
    "Nunca tive relações sexuais com alguém que não falava a mesma língua.",
    "Nunca fiz sexo em uma sauna ou sauna a vapor.",
    "Nunca tive relações sexuais com alguém que fosse virgem.",
    "Eu nunca tive fetiches considerados 'estranhos'.",
    "Eu nunca fiz sexo em troca de algum benefício (carona, favor, dinheiro etc.).",
    "Eu nunca traí alguém e ainda fui pra cama com a pessoa depois.",
    "Eu nunca pratiquei sexo por telefone ou vídeo chamada.",
    "Eu nunca fui em um motel sozinho(a) com alguém 'proibido'.",
    "Eu nunca usei o nome de outra pessoa durante o sexo.",
    "Eu nunca menti que cheguei ao orgasmo só pra acabar logo.",
    "Eu nunca gravei um vídeo íntimo com alguém.",
    "Eu nunca usei brinquedos sexuais em casal.",
    "Eu nunca fiz sexo com alguém só por vingança.",
    "Eu nunca tive uma experiência com alguém do mesmo sexo.",
    "Eu nunca fui para uma casa de swing."
  ];
  