const perguntasPopular = [
    "Eu nunca menti para meus pais sobre onde estava.",
    "Eu nunca fiz xixi na piscina.",
    "Eu nunca traí meu parceiro.",
    "Eu nunca roubei algo de uma loja.",
    "Eu nunca pulei uma cerca para entrar em uma festa.",
    "Eu nunca fui preso.",
    "Eu nunca experimentei drogas ilegais.",
    "Eu nunca fiquei acordado a noite toda.",
    "Eu nunca bebi tanto que vomitei.",
    "Eu nunca menti para meus pais sobre com quem eu estava.",
    "Eu nunca contei um segredo de um amigo para outra pessoa.",
    "Eu nunca joguei jogos de azar com dinheiro real.",
    "Eu nunca fui expulso da escola.",
    "Eu nunca quebrei um osso enquanto estava bêbado.",
    "Eu nunca menti no meu currículo para conseguir um emprego.",
    "Eu nunca acordei em um lugar estranho sem saber como cheguei lá.",
    "Eu nunca causei um acidente de carro.",
    "Eu nunca disse 'eu te amo' apenas para conseguir algo que queria.",
    "Eu nunca fiz xixi na rua enquanto estava bêbado.",
    "Eu nunca passei um dia inteiro assistindo TV.",
    "Eu nunca passei a noite inteira em um bar.",
    "Eu nunca fui pego(a) roubando.",
    "Eu nunca fui a um encontro às cegas.",
    "Eu nunca menti sobre minha idade para entrar em um lugar.",
    "Eu nunca fui preso(a) por estar bêbado(a) em público.",
    "Eu nunca beijei alguém para me vingar.",
    "Eu nunca usei o nome de outra pessoa para conseguir uma reserva em um restaurante.",
    "Eu nunca contei uma mentira em um tribunal.",
    "Eu nunca tive um relacionamento com alguém só por interesse financeiro.",
    "Eu nunca fingi estar doente para sair de um compromisso.",
    "Eu nunca fui em um encontro com alguém que era comprometido com outra pessoa.",
    "Eu nunca bati em alguém durante uma briga.",
    "Eu nunca fiz uma tatuagem que me arrependi depois.",
    "Eu nunca fui pego(a) fazendo algo ilegal.",
    "Eu nunca traí um amigo.",
    "Eu nunca roubei algo do trabalho.",
    "Eu nunca enviei uma mensagem de texto enquanto dirigia.",
    "Eu nunca usei drogas no trabalho.",
    "Eu nunca fui suspenso(a) da escola.",
    "Eu nunca fui a um show sem ingresso.",
    "Eu nunca menti sobre minha identidade na internet.",
    "Eu nunca fiquei com alguém só por pena.",
    "Eu nunca participei de uma briga de rua.",
    "Eu nunca beijei alguém em uma festa.",
    "Eu nunca mandei mensagem e me arrependi depois.",
    "Eu nunca fui ignorado propositalmente por alguém que eu gostava.",
    "Eu nunca flertei com alguém comprometido.",
    "Eu nunca stalkeei o Ex de alguém.",
    "Eu nunca apaguei mensagens pra evitar briga.",
    "Eu nunca mandei mensagem errada pra pessoa errada.",
    "Eu nunca fiquei com alguém e depois me arrependi.",
    "Eu nunca fiz drama pra conseguir o que queria.",
    "Eu nunca fiquei com duas pessoas na mesma semana.",
    "Eu nunca falei mal de alguém e a pessoa ouviu.",
    "Eu nunca fui rejeitado por alguém na frente dos outros.",
    "Eu nunca fui em um encontro só por educação.",
    "Eu nunca usei um 'desculpa' só para sair de uma situação.",
    "Eu nunca fingi que não vi alguém para evitar conversa.",
    "Eu nunca fiquei com alguém e não lembrava o nome depois.",
    "Eu nunca disse 'eu te amo' sem sentir de verdade.",
    "Eu nunca fingi estar ocupado pra não sair com alguém.",
    "Eu nunca tive um crush por alguém comprometido.",
    "Eu nunca fiquei com alguém só por tédio.",
    "Eu nunca fui bloqueado por alguém sem saber o motivo.",
    "Eu nunca usei alguém pra esquecer outra pessoa.",
    "Eu nunca mandei indireta nas redes sociais.",
    "Eu nunca deletei fotos pra esconder o passado.",
    "Eu nunca me arrependi no meio de um encontro.",
    "Eu nunca liguei bêbado pra alguém.",
    "Eu nunca fiquei com alguém só por aparência.",
    "Eu nunca deixei de responder só pra me fazer de difícil.",
    "Eu nunca inventei desculpa pra sair de um encontro chato.",
    "Eu nunca causei ciúmes de propósito.",
    "Eu nunca disse que li um livro clássico só para parecer culto.",
    "Eu nunca fingi estar dormindo no transporte público para não ceder o meu lugar a alguém.",
    "Eu nunca postei dancinha no TikTok querendo que uma pessoa específica visse.",
    "Eu nunca fui expulso da sala de aula.",
    "Eu nunca desmaiei na rua.",
    "Nunca peguei carona com estranhos.",
    "Eu nunca fui parado por policiais.",
    "Nunca andei a cavalo.",
    "Eu nunca quebrei um osso.",
    "Eu nunca quebrei um dente.",
    "Eu nunca criei uma conta falsa nas redes sociais.",
    "Eu nunca tive uma experiência paranormal.",
    "Eu nunca tive algum perfil de rede social hackeado.",
    "Eu nunca tive paralisia do sono.",
    "Eu nunca fiquei preso no elevador.",
    "Eu nunca tentei cortar meu próprio cabelo.",
    "Eu nunca pintei o cabelo de alguma cor estranha.",
    "Nunca cantei em um karaokê na frente de várias pessoas.",
    "Eu nunca apareci na TV.",
    "Eu nunca passei mal em um parque de diversões.",
    "Eu nunca corri da polícia.",
    "Eu nunca pedi dinheiro no sinal.",
    "Eu nunca me arrependi imediatamente após enviar uma mensagem.",
    "Eu nunca levei um tapa no rosto.",
    "Eu nunca dei um tapa no rosto de alguém.",
    "Eu nunca participei de uma briga.",
    "Eu nunca chorei no transporte público.",
    "Eu nunca passei mais de dois dias sem tomar banho.",
    "Eu nunca olhei o celular de alguém sem que a pessoa soubesse.",
    "Eu nunca fui demitido.",
    "Eu nunca dormi na rua.",
    "Nunca peguei comida do lixo e comi.",
    "Eu nunca consegui algo de graça dando em cima de alguém.",
    "Nunca caí na rua porque estava olhando o celular.",
    "Eu nunca tive um vídeo constrangedor postado na internet.",
    "Eu nunca quebrei algo na casa de alguém e escondi.",
    "Eu nunca saí de uma festa ou bar sem pagar.",
    "Eu nunca me gabei por algo que não fiz.",
    "Eu nunca menti tanto sobre algo que acreditei que fosse verdade.",
    "Eu nunca sofri bullying na escola.",
    "Eu nunca segurei a mão da pessoa errada na rua.",
    "Eu nunca fui expulso de uma festa.",
    "Nunca fiquei com mais de 5 pessoas em uma festa.",
    "Nunca beijei alguém que eu não conhecia.",
    "Eu nunca fiquei com o irmão/irmã de um amigo.",
    "Eu nunca dormi no ônibus e perdi o meu ponto.",
    "Eu nunca fiquei apaixonado por algum professor.",
    "Eu nunca fui assaltado.",
    "Eu nunca recebi flores.",
    "Eu nunca menti para meus pais sobre aonde estava indo.",
    "Eu nunca fiz xixi em uma piscina do lado dos meus amigos.",
    "Eu nunca usei Crocs.",
    "Eu nunca vomitei na frente de outras pessoas.",
    "Eu nunca soltei pum em um elevador e fingi que não fui eu.",
    "Eu nunca segui a pessoa errada na rua.",
    "Eu nunca deixei meu celular cair na privada.",
    "Eu nunca fui em uma festa sem ser chamado.",
    "Eu nunca beijei alguém famoso."
  ];