const perguntasRelacionamento = [
    "Eu nunca tive um sonho molhado com alguém que está aqui.",
    "Nunca me senti atraído(a) pelo(a) pai/mãe de algum amigo.",
    "Eu nunca enviei fotos íntimas para a pessoa errada.",
    "Eu nunca fiquei com alguém do mesmo gênero que eu.",
    "Eu nunca fiquei com irmãos gêmeos.",
    "Eu nunca fiquei com mais de uma pessoa no mesmo dia.",
    "Eu nunca fui num cabaré.",
    "Eu nunca mandei a mesma fotografia ousada para mais de uma pessoa.",
    "Eu nunca encontrei com alguém do Tinder.",
    "Eu nunca beijei ninguém depois de ter vomitado na balada.",
    "Eu nunca tive um 'amigo colorido' ou 'amigo com benefícios'.",
    "Eu nunca vi meus pais em um momento de intimidade.",
    "Eu nunca sonhei com algum professor.",
    "Eu nunca fiquei com alguém desta roda.",
    "Eu nunca fiquei com alguém que eu não sabia o nome.",
    "Eu nunca fiquei com uma pessoa e depois nunca mais falei com ela.",
    "Eu nunca fiquei com alguém no meio da rua.",
    "Eu nunca usei o Tinder.",
    "Eu nunca assisti a um filme para maiores de idade.",
    "Eu nunca marquei um encontro e não apareci sem avisar.",
    "Eu nunca disse 'eu te amo' apenas para ficar com alguém.",
    "Eu nunca dormi enquanto estava ficando com alguém.",
    "Eu nunca escondi uma marca no pescoço com uma blusa gola alta ou maquiagem.",
    "Eu nunca fiquei com alguém na universidade.",
    "Eu nunca fiquei com alguém no banheiro de uma festa.",
    "Eu nunca fiquei com alguém 20 anos (ou mais) mais velho que eu.",
    "Eu nunca usei uma fantasia ousada.",
    "Eu nunca usei o Tinder enquanto namorava.",
    "Eu nunca fiquei com um(a) vizinho(a).",
    "Eu nunca flertei com outra pessoa mesmo estando comprometido(a).",
    "Eu nunca disse 'eu te amo' por educação.",
    "Eu nunca fiquei com alguém comprometido.",
    "Eu nunca fiquei com ex de amigo(a).",
    "Eu nunca 'furei o olho' de ninguém.",
    "Eu nunca fiquei com irmão/irmã de amigo(a).",
    "Eu nunca enviei uma mensagem comprometedora para a pessoa errada.",
    "Eu nunca fiz simpatia para conquistar ou reconquistar alguém.",
    "Eu nunca fiquei com uma pessoa na frente de outra por vingança.",
    "Eu nunca acordei sem lembrar do nome da pessoa com quem fiquei na noite anterior.",
    "Eu nunca troquei o nome do(a) crush/namorado(a).",
    "Eu nunca mexi no celular do(a) parceiro(a) por estar desconfiado(a) de algo.",
    "Eu nunca provoquei uma pessoa comprometida.",
    "Eu nunca fui a um encontro às cegas.",
    "Eu nunca tive vontade de sair correndo depois de um beijo.",
    "Eu nunca curti várias fotos antigas de alguém no Instagram para a pessoa me notar.",
    "Eu nunca beijei alguém que um dia jurei que jamais ficaria.",
    "Eu nunca entupi a privada no banheiro da casa do(a) parceiro(a).",
    "Eu nunca fiquei com alguém por interesse.",
    "Eu nunca sumi depois de ficar com alguém.",
    "Eu nunca fiquei com mais de uma pessoa do Tinder em uma mesma semana.",
    "Eu nunca dei 'ghost' em alguém.",
    "Eu nunca levei 'ghost' de alguém.",
    "Eu nunca fiquei com alguém bem mais novo que eu.",
    "Eu nunca inventei um(a) namorado(a) imaginário(a) para fazer ciúmes no ex.",
    "Eu nunca fiz 'foto isca' no Instagram.",
    "Eu nunca inventei uma desculpa para parar de falar com alguém no Tinder.",
    "Eu nunca fiquei super mal por uma '_situationship_' que não foi para frente.",
    "Eu nunca fiquei com alguém para superar outra pessoa e acabei precisando superar os dois.",
    "Eu nunca usei truques de conquista durante um encontro.",
    "Eu nunca dei em cima do namorado(a) de algum amigo.",
    "Eu nunca disse 'eu te amo' para alguém que eu não amava de verdade.",
    "Nunca me apaixonei à primeira vista.",
    "Eu nunca passei a madrugada mandando mensagem para alguém.",
    "Eu nunca fui ignorado no WhatsApp por alguém que eu gostava.",
    "Eu nunca inventei boatos sobre um(a) ex-namorado(a).",
    "Eu nunca traí alguém.",
    "Eu nunca implorei para algum(a) ex voltar para mim.",
    "Eu nunca estive em um relacionamento aberto.",
    "Eu nunca tive um namorado virtual.",
    "Eu nunca me arrependi de ter namorado alguém.",
    "Nunca beijei meu melhor amigo.",
    "Eu nunca duvidei sobre minha orientação sexual.",
    "Eu nunca assisti a uma série sozinha que havia combinado de ver com meu namorado/minha namorada.",
    "Eu nunca namorei uma pessoa para tentar esquecer outra.",
    "Eu nunca sumi depois de um primeiro encontro ruim.",
    "Eu nunca fiquei com alguém comprometido(a).",
    "Eu nunca terminei com alguém por mensagem.",
    "Eu nunca menti sobre meu estado civil.",
    "Eu nunca fiz voz de bebê para falar com um namorado/uma namorada.",
    "Eu nunca fingi receber uma mensagem/ligação para sair de um encontro ruim.",
    "Eu nunca falei sobre meu ex em um primeiro encontro.",
    "Eu nunca fui apaixonado(a) por mais de uma pessoa ao mesmo tempo.",
    "Eu nunca fuxiquei o celular do(a) namorado(a).",
    "Eu nunca causei ciúmes em alguém de propósito.",
    "Eu nunca participei de uma sessão de terapia em casal.",
    "Eu nunca tive um encontro às cegas."
  ];